// movie-react-front/src/App.js
import {BrowserRouter, Link, Route} from 'react-router-dom';
import React from 'react';
import './Style.css';
import Homepage from './Homepage';
import LoginForm from './LoginForm';
import NavigationBar from './NavigationBar';
import Register from './Register';
import Movie from './Movie';
import Logout from './Logout';
import AdminTools from './AdminTools';
import Account from './Account';


export default class App extends React.Component {

  constructor(props){
    super(props);
    this.state = {
      userData: '',
      userID: undefined,
      isAuthenticated: false
    }
  }

  componentDidMount(){
    this.setState({
      userData: window.sessionStorage.getItem("currentUser"),
      userID: window.sessionStorage.getItem("userID"),
      isAuthenticated: window.sessionStorage.getItem("isLoggedIn"),
      isAdmin: window.sessionStorage.getItem("isAdmin"),
    })
  }

  setUserID = (userID) => {
    this.setState({userID: userID})
  }

  render() {
    const isAuthenticated = this.state.isAuthenticated;
    const isAdmin = this.state.isAdmin;
    return (
      <div className="App">
        <BrowserRouter>
          <NavigationBar isLoggedIn={isAuthenticated} isAdmin={isAdmin} user_id={this.state.userID}/>
          <section className="content">
            <Route exact path="/">
              <Homepage userID={this.state.userID} />
            </Route>
            <Route exact path="/login">
              <LoginForm setUserID={this.setUserID}/>
            </Route>
            <Route exact path="/movie" component={Movie}/>
            <Route exact path="/logout" component={Logout}/>
            <Route exact path="/register" component={Register}/>
            <Route exact path="/admin" component={AdminTools}/>
            <Route exact path="/account" component={Account}/>
          </section>
        </BrowserRouter>
      </div>
    );
  }
}

// movie-vue-front/src/App.vue
<template>
  <div id="app">
    <NavigationBar :isLoggedIn="isAuthenticated" :isAdmin="isAdmin" :user_id="userID" />
    <router-view></router-view>
  </div>
</template>

<script>
import "./assets/Style.css"
import NavigationBar from "./components/NavigationBar"
export default {
  name: 'App',
  data() {
    return {
      userData: '',
      userID: undefined,
      isAuthenticated: false,
      isAdmin: false,
    }
  },
  components: {NavigationBar},
  created() {
    this.userData = window.sessionStorage.getItem("currentUser");
    this.userID = window.sessionStorage.getItem("userID");
    this.isAuthenticated = window.sessionStorage.getItem("isLoggedIn");
    this.isAdmin = window.sessionStorage.getItem("isAdmin");
  },
};
</script>

<style>
/* @import './assets/Style.css'; */
</style>
