// movie-vue-front/src/components/ResetPage.vue
<template>
  <div className="content">
    <br />
    <label>Password: </label>
    <input v-model="password" class="password" type="password" />
    <label>Confirm Password: </label>
    <input v-model="passwordConfirm" class="password" type="password" />
    <br />
    <br />
    <button v-on:click="resetPassword" id="resetButton">Reset Password</button>
    <img id="loadingIcon" class="hidden loadingIcon" src="https://upload.wikimedia.org/wikipedia/commons/c/c7/Loading_2.gif" />
  </div>
</template>

<script>
export default {
  data() {
    return {
      password: "",
      passwordConfirm: "",
    };
  },
  methods: {
    resetPassword() {
    //   console.log(window.location.pathname);
      if (this.password === this.passwordConfirm) {
        document.getElementById("resetButton").classList = "hidden"
        document.getElementById("loadingIcon").classList = "loadingIcon"
        fetch(`http://localhost:8080${window.location.pathname}`, {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
          },
          body: new URLSearchParams({
            password: this.password,
          }),
        })
          .then((res) => res.json())
          .then((data) => {
            console.log(data);
            //TODO Give user prompt that password was changed
            window.location.href = "/"
          });
      }
    },
  },
};
</script>

<style>
.hidden{
    display: none;
}
.loadingIcon{
    width: 30px;
}
</style>

// movie-react-front/src/ResetPage.js
import React from 'react';

//Self contained, should have a setter for the parent for when user auths
export default class EmailConfirmation extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            password: '',
            passwordConfirm: ''
        }
    }

    handlePassword = evt => {
        this.setState({password: evt.target.value});
    }

    handlePasswordConfirm = evt => {
        this.setState({passwordConfirm: evt.target.value});
    }

    resetPassword = () => {
        console.log(window.location.pathname)
        if(this.state.password === this.state.passwordConfirm) {
            fetch(`http://localhost:8080${window.location.pathname}`, {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
                },
                body: new URLSearchParams({
                    password: this.state.password,
                })
              })
            .then(res => res.json())
            .then(data => console.log(data));
        }
    }
    
    render() {
        return (
            <div className="content">
                <h2>Provide your email to reset your password</h2>
                <br/>
                <label>Email: </label>
                <input type="password" value={this.state.password} onChange={this.handlePassword} placeholder="New Password..."/>
                <input type="password" value={this.state.passwordConfirm} onChange={this.handlePasswordConfirm} placeholder="Confirm New Password..."/>
                <br/>
                <br/>
                {/* <input type="submit" value="Submit"/> */}
                <button onClick={this.resetPassword}>Reset Password</button>
            </div>
        )
    }
}
