// movie-react-front/src/ReviewList.js
import React from 'react';
import Review from './Review';
//Requires movie id through props
export default class ReviewList extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            user_review_id: undefined,
            userHasReview: false,
            isAdmin: (window.sessionStorage.getItem("isAdmin") === "1"),
        }
    }

    componentDidMount() {
        this.props.refreshReviews()
    }

    handleReview = (evt, i) => {
        this.props.handleReview(evt, i)
    }

    handleRating = (evt, i) => {
        this.props.handleRating(evt, i)
    }

    handleDelete = (id) => {
        console.log(id)
        fetch('http://localhost:8080/api/reviews', {
            method: 'DELETE',
            headers: {
              'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
            },
            body: new URLSearchParams({
                review_id:id
            })
          })
        .then(res => res.json())
        .then(data => {
            if(data){
                console.log(data)
                this.props.refreshReviews();
            }
        })
    }

    renderReviews = () => {
        var reviews = [];
        for (let i = 0; i < this.props.reviews.length; i++) {
            if (this.props.reviews[i][1] === this.props.user_review_id) {
                reviews.push(
                    <>
                        {this.state.isAdmin? <button onClick={()=>this.handleDelete(this.props.reviews[i][0])}>Yeet Review</button>:""}
                        <Review key={i} editReview={this.props.editReview} index={i} handleRating={this.handleRating} handleReview={this.handleReview} refreshReviews={this.props.refreshReviews} isEditable={true} review_body={this.props.reviews[i][3]} rating={this.props.reviews[i][4]} user_id={this.props.reviews[i][1]} review_id={this.props.reviews[i][0]} />
                    </>
                )
            } else {
                reviews.push(
                    <>
                        {this.state.isAdmin? <button onClick={()=>this.handleDelete(this.props.reviews[i][0])}>Yeet Review</button>:""}
                        <Review key={i} editReview={this.props.editReview} index={i} handleRating={this.handleRating} handleReview={this.handleReview} refreshReviews={this.props.refreshReviews} isEditable={false} review_body={this.props.reviews[i][3]} rating={this.props.reviews[i][4]} user_id={this.props.reviews[i][1]} review_id={this.props.reviews[i][0]} />
                    </>
                )
            }
        }

        return reviews;
    }

    render() {
        return (
            <>
                {this.renderReviews()}
            </>
        )
    }
}

// movie-vue-front/src/components/ReviewList.vue
<template>
  <div class="ReviewList">
    <div class="review-container" v-for="(review, index) in reviews" v-bind:key="review.id">
       <button v-if="isAdmin" v-on:click="() => this.handleDelete(reviews[index][0])">Remove Review</button>
       <Review v-bind:editReview="editReview" v-bind:index="index" v-bind:handleRating="handleRating" v-bind:handleReview="handleReview" v-bind:refreshReviews="refreshReviews" v-bind:isEditable="reviews[index][1] === user_review_id" v-bind:review_body="reviews[index][3]" v-bind:rating="reviews[index][4]" v-bind:user_id="reviews[index][1]" v-bind:review_id="reviews[index][0]"/>
    </div>
  </div>
</template>

<script>
import Review from "./Review.vue"
export default {
  name: "reviewlist",
  components: {Review},
  props: [
    "editReview",
    "handleRating",
    "handleReview",
    "reviews",
    "user_review_id",
    "refreshReviews",
    "movie_id",
  ],
  data() {
    return {
      isAdmin: window.sessionStorage.getItem("isAdmin") === "1",
    };
  },
  methods: {
    handleDelete(id) {
      console.log(id);
      fetch("http://localhost:8080/api/reviews", {
        method: "DELETE",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        },
        body: new URLSearchParams({
          review_id: id,
        }),
      })
        .then((res) => res.json())
        .then((data) => {
          if (data) {
            console.log(data);
            this.refreshReviews();
          }
        });
    },
  },
};
</script>

<style>
</style>
